export const BASE_URL = "http://192.168.1.238:2237";
export const LOGIN_URL ="/NuTimeSheetApi/UserProfile/userLoginValidation";
export const CREATE_TASK_URL ="/NuTimeSheetApi/Project/Task/CreateTaskWithoutUserIds"
export const SAVE_TIMESHEET_URL ="/NuTimeSheetApi/TimeSheet/saveTimeSheetEntry"
export const GET_ALL_ASSOCIATES_URL ="/NuTimeSheetApi/UserProfile/getAllAssociate"
export const ASSIGN_TASK_TO_PROJECT_MEMBER_URL ="/NuTimeSheetApi/Project/assignTaskToProjectMember"
export const ADD_MEMBER_TO_PROJECT_URL ="/NuTimeSheetApi/Project/addMemberToProject"
export const CREATE_BASIC_PROJECT_URL ="/NuTimeSheetApi/Project/createBasicProject"
export const GET_ALL_PROFILE_URL ="/NuTimeSheetApi/UserProfile/getAllprofile"
export const EDIT_PROJECT_DETAILS_URL ="/NuTimeSheetApi/Project/editProjectDetails"
export const EDIT_TASK_DETAILS_URL ="/NuTimeSheetApi/Project/editTaskDetails"
export const EDIT_SAVED_TIMESHEET_URL ="/NuTimeSheetApi/TimeSheet/editSavedTimeSheet"
export const GET_PROJECT_BY_PROJECTID_URL ="/NuTimeSheetApi/Project/getProjectByProjectId"
export const GET_PROJECT_BY_USERID_URL ="/NuTimeSheetApi/Project/getProjectByUserId"
export const REMOVE_MEMBER_FROM_PROJECT_URL ="/NuTimeSheetApi/Project/removMemberFromProject"
export const REMOVE_USER_FROM_TASK_URL ="/NuTimeSheetApi/Project/removeUserFromTask"
export const GET_SUBMITTED_TIMESHEET_URL ="/NuTimeSheetApi/TimeSheet/getSubmittedTimeSheet?loggedInUserId="
export const GET_SAVED_TIMESHEET_URL ="/NuTimeSheetApi/TimeSheet/getSavedTimeSheet"
export const SUBMIT_TIMESHEET_URL ="/NuTimeSheetApi/TimeSheet/submitTimeSheet"
export const DELETE_TIMESHEET_ENTRY_URL ="/NuTimeSheetApi/TimeSheet/deleteTimeSheetEntry"
export const APPROVE_SUBMITTED_TIMESHEET_URL ="/NuTimeSheetApi/TimeSheet/approveSubmittedTimeSheets"
export const REJECT_SUBMITTED_TIMESHEET_URL ="/NuTimeSheetApi/TimeSheet/rejectSubmittedTimeSheets"
export const GET_REJECTED_TIMESHEET_URL ="/NuTimeSheetApi/TimeSheet/getRejectedTimeSheetEntryByAssociate?profileId="
export const GET_APPROVED_TIMESHEET_URL ="/NuTimeSheetApi/TimeSheet/getApprovedTimeSheetEntryByAssociate?profileId="
export const EDIT_USER_DETAILS_URL ="/NuTimeSheetApi/UserProfile/editUserDetails"

//export const BASE_URL = "http://106.51.0.187:2237";